APP_STL := gnustl_static

APP_CPPFLAGS := -frtti -std=c++11 -fsigned-char
APP_LDFLAGS := -latomic

CC_ENABLE_SCRIPT_BINDING :=1

APP_CPPFLAGS += -DANDROID
APP_CPPFLAGS += -DCC_ENABLE_SCRIPT_BINDING=1
APP_CPPFLAGS += -DCC_USE_PHYSICS=0
APP_CPPFLAGS += -DCC_USE_3D_PHYSICS=0
APP_CPPFLAGS += -DCC_ENABLE_CHIPMUNK_INTEGRATION=0
APP_CPPFLAGS += -DCC_ENABLE_BOX2D_INTEGRATION=0
APP_CPPFLAGS += -DCC_ENABLE_BULLET_INTEGRATION=0
APP_CPPFLAGS += -DCC_USE_NAVMESH=0

ifeq ($(NDK_DEBUG),1)
  APP_CPPFLAGS += -DCOCOS2D_DEBUG=1
  APP_OPTIM := debug
else
  APP_CPPFLAGS += -DNDEBUG
  APP_OPTIM := release
endif

